import { readFileSync,writeFileSync } from 'node:fs';
const dir='docs/phase1_5',read=name=>JSON.parse(readFileSync(`${dir}/data/${name}`,'utf8'));
const fmt=value=>value===null?'—':Math.round(value).toLocaleString('en-US');
function distribution(values){const sorted=values.filter(x=>x!==null&&Number.isFinite(x)).sort((a,b)=>a-b);if(!sorted.length)return '—';return [.1,.5,.9].map(p=>fmt(sorted[Math.floor((sorted.length-1)*p)])).join(' / ');}
const definitions=`Policies review the production CompanyView every14 days. All commands are real player commands. No policy receives WorldState, private psychology, exact exit intent or random thresholds. Same seeds benchmark-001…100, NT$500,000, three founding employees. Monthly checkpoints at days90/181/365/730; day1826 includes the2028 leap day. Terminal checkpoint values carry forward frozen shutdown state, explicitly tagged terminalCarryForward. Diagnostic fields are post-run only. Every session independently replays its complete command history and round-trips a validated save.

- passive: advance only.
- conservative: sustainable workload; founder salary NT$10,000 from day0; features until launch, then quality; if runway<3 after launch, dismiss highest-paid non-founder while more than one remains; recruit an Engineer at NT$35,000 only when cash>NT$1m and runway>12, up to4 people.
- aggressive: growth workload, features until launch then quality; recruit Engineers at NT$35,000, up to6, while cash>NT$150k and runway>1.5.
- employee-first: sustainable workload; no cuts/recruitment; features then quality; observable distressed non-founders receive at most two10% raises if runway>3.
- product-first: balanced workload; one early Engineer if initial runway>4; features then quality.
- lean (sensitivity extension): sustainable, dismiss CTO at day0, retain founder salary NT$25,000 and Engineer salary NT$30,000; features then quality; no further recruitment. This tests a distinct cost path without founder pay deferral. It is a measured policy, not a product feature.
`;
let benchmark='# Phase1.5 strategy benchmark\n\n'+definitions;
for(const horizon of [730,1826]){
 const report=read(`strategies-${horizon}.json`);benchmark+=`\n## ${horizon} days — ${report.seeds} seeds per policy\n\nRuntime ${report.runtimeMs}ms; replay/restore mismatches ${report.replayOrRestoreMismatches}. Six policies,${report.rows.length} sessions. Percentiles below are P10 / P50 / P90; NT dollars. No single combined score is used. Bankruptcy timing is conditional on failure; other columns include frozen terminal sessions. Surviving contracts and active roster in a stopped company are frozen bookkeeping, not continuing operations.\n\n`;
 benchmark+='|Policy|Survive|Bankruptcy day|Cash|MRR|Payroll|Cumulative booked revenue|People|Customers|Runway (finite only)|\n|---|---:|---|---|---|---|---|---|---|---|\n';
 for(const policy of [...new Set(report.rows.map(r=>r.policy))]){
  const rows=report.rows.filter(r=>r.policy===policy);benchmark+=`|${policy}|${rows.filter(r=>!r.bankrupt).length}/${rows.length}|${distribution(rows.map(r=>r.bankruptcyTick))}|${distribution(rows.map(r=>r.cashNTD))}|${distribution(rows.map(r=>r.mrrNTD))}|${distribution(rows.map(r=>r.payrollNTD))}|${distribution(rows.map(r=>r.revenueNTD))}|${distribution(rows.map(r=>r.employees))}|${distribution(rows.map(r=>r.customers))}|${distribution(rows.map(r=>r.runway))}|\n`;
 }
 benchmark+='\n|Policy|Resignations total|Churn total|Launch day P10/50/90|Major events P10/50/90|Warnings P10/50/90|Longest important-event gap P10/50/90|\n|---|---:|---:|---|---|---|---|\n';
 for(const policy of [...new Set(report.rows.map(r=>r.policy))]){const rows=report.rows.filter(r=>r.policy===policy);benchmark+=`|${policy}|${rows.reduce((s,r)=>s+r.resignations,0)}|${rows.reduce((s,r)=>s+r.customerChurn,0)}|${distribution(rows.map(r=>r.launchTick))}|${distribution(rows.map(r=>r.majorEvents))}|${distribution(rows.map(r=>r.majorWarnings))}|${distribution(rows.map(r=>r.quietGapDays))}|\n`;}
 if(horizon===730){benchmark+='\n|Policy|3mo survive|6mo survive|12mo survive|24mo survive|Stable employee share mean at3/6/12/24mo|\n|---|---|---|---|---|---|\n';for(const policy of [...new Set(report.rows.map(r=>r.policy))]){const rows=report.rows.filter(r=>r.policy===policy),at=d=>rows.map(r=>r.checkpoints.find(c=>c.tick===d));benchmark+=`|${policy}|${[90,181,365,730].map(d=>`${at(d).filter(c=>!c.bankrupt).length}/100`).join('|')}|${[90,181,365,730].map(d=>(at(d).reduce((s,c)=>s+(c.observableHealth['狀態穩定']??0),0)/rows.length*100).toFixed(1)+'%').join(' / ')}|\n`;}}
}
benchmark+=`\n## Interpretation and limitations\n\nConservative survives100/100; lean73/100; passive3/100; the sampled aggressive, employee-first and product-first policies0/100 at both horizons. Conservative dominates survival within this set, a potential design concern; this does not establish global optimality. Lean demonstrates a second viable, riskier path without reducing CEO salary. Aggressive hiring does not outperform conservative here. More engineers accelerate launch but recurring cost can outpace the single weekly customer-acquisition opportunity. Acquisition pace, rather than development capacity alone, limits early hiring returns. Employee stability alone cannot pay payroll. Salary raises above already-met expectations have modest production effects and real cash costs. No normal policy session produced resignation before insolvency; employee drama was investigated separately with actual underpayment and post-survival workload commands.\n\n“Recovery events” in raw rows count transitions from runway<3 to>=3 between policy observations while alive. These can be temporary changes between monthly closes; passive has such transitions too. They must NOT be interpreted as intervention success. The controlled financial and employee branches provide the causal recovery evidence. FailureFactors allow multiple contributing classifications. Hiring exposure is association, not proof that any hire alone caused failure; independent branch comparisons isolate a decision. Monthly MRR is not booked revenue. Numeric runway percentiles exclude self-sufficient/null values and round for table readability; raw JSON retains exact values and per-seed outcomes. Health summaries are qualitative categories, not hidden scores; bankrupt rosters are frozen, so “healthy” does not mean an operational firm. No human study has validated the10-second urgency target.\n\nRaw evidence: data/strategies-730.json, strategies-1826.json, decision-branches.json, warning-traces.json and representative validated saves. Counterfactual CLI: pnpm exec tsx scripts/counterfactual.ts input.json output.json; input {save,a:[commands],b:[commands],days}. Omniscient diagnostic output stays developer-only.\n`;
const cheap=read('cheap-offer-probe.json');
benchmark+=`\n## Pathological offer probe — a release concern\n\nTen shared seeds benchmark-001…010, same aggressive policy but each new offer is NT$1/month. ${cheap.rows.filter(r=>!r.bankrupt).length}/10 survive2years, compared with0/10 at NT$35,000. This is a deliberately pathological legal-input sensitivity, not a recommended strategy and not combined with the normal strategy ranking. New expectations initialize to the offered wage (NT$1), so low offered wages are treated as meeting expectations. This supports a concrete balance exploit, not “active management mastery.” No salary minimum or expectation equation was changed: choosing market expectations/minimum offers and replay-version behavior needs explicit evidence-backed iteration. Raw: data/cheap-offer-probe.json.\n`;
writeFileSync(`${dir}/STRATEGY_BENCHMARK.md`,benchmark);
let playtest='# Phase1.5 gameplay-style sessions\n\nOperator: Codex through actual Playwright-controlled Chrome UI, not human participant research. Each starts at2026-01-01, NT$500,000, CEO/CTO/Engineer, Atlas, seed stated below. Native browser plugin unavailable; existing Playwright/Chrome workflow used. All actions pass through normal UI→Worker→application→simulation→IndexedDB, then a real export download. Before and after UX sessions are recorded separately. No direct world mutation, hidden-information policy or headless command injection was used for these sessions.\n\n';
const interpretations={conservative:'Founder salary reduced to10k and sustainable atday0. Atday84 dismiss CTO and switch to quality. Tradeoff: slower launch but lower payroll. Survived12months. This layoff timing is a curated UI decision, not the benchmark policy.',aggressive:'Growth with two immediate35k engineers; quality atday56. Product launch improves, but payroll exceeds early contracts; shutdown atday90, observed afterweek13/day91. No employee-health drama before cash failure.', 'poor-decisions-recovery':'Immediate35k hire, CTO salary cut to0 and growth. Atday56 dismiss extra hire, founder salary0, restore CTO40k, sustainable and quality. Survived12months. Recovery increases retention cost while founder bears a significant compensation sacrifice; zero founder pay is legal but not free of dissatisfaction.','employee-stability':'Sustainable without payroll cuts, quality atday84. Staff remain stable but slow launch and unchanged payroll exhaust cash atday151, observed atday154. Retention alone is insufficient.'};
for(const style of Object.keys(interpretations)){
 const before=read(`ui-playthroughs/${style}.notes.json`),save=read(`ui-playthroughs/${style}.save.json`),result=before.notes.at(-1).result;
 playtest+=`## ${style} — ${before.seed}\n\n${interpretations[style]}\n\nResult: day${result.tick}; cash NT$${fmt(result.cashNTD)}; bankrupt=${result.bankrupt}; browser errors${before.notes.at(-1).errors.length}.\n\nDecisions: ${before.notes.filter(n=>n.decision).map(n=>JSON.stringify(n)).join('; ')}.\n\nSignificant event evidence (actual saved events):\n\n`;
 for(const event of save.world.events.filter(e=>['ProductLaunched','EmployeeConcernRaised','EmployeeResigned','EmployeeFired','RunwayWarning','CompanyBankrupt'].includes(e.type)).slice(0,12))playtest+=`- ${event.date}, day${event.tick}, ${event.type}, ${JSON.stringify(event.payload)}.\n`;
 playtest+='\nObserved UX: original week advancement only changed figures; no consolidated summary. Recruitment disclosed salary but did not preview company payroll/runway. Runway assumed current rates, while historical earned payroll remained due; the upcoming close was unclear. Product labels explained speed/quality tradeoff reasonably. Employee history listed titles, requiring another search for causes. After focused changes, weekly summary, held-contract month-close forecast, cost previews, qualitative warnings, linked employee events and priority filtering address these specific gaps. No claim that a human player found every issue within10 seconds.\n\nFull dated observations and command histories: data/ui-playthroughs/'+style+'.notes.json and .save.json.\n\n';
}
playtest+='## After-change reproduction\n\nAll four sessions were repeated through the same actual UI controls; every final save hash matches its before-change counterpart. Full notes: data/ui-playthroughs-after/. Each has0 console/page errors. Summaries and forecasts are display-only. These sessions document concrete agent-operated play, not human learnability or a measured10-second response time. A local replay attempt timed out during browser/server lifecycle contention; an overlapping E2E run then lost its shared preview server. These failures were retained and resolved by closing only owned stale test processes and rerunning sequentially; final acceptance retains every original assertion.\n';
writeFileSync(`${dir}/PLAYTEST_NOTES.md`,playtest);
const warnings=read('warning-traces.json');
let story='# Phase1.5 story and causal audit\n\nThese chains use saved events, real commands and structured cause classifications. They are not fictional scenes. Causal links, time ordering and controlled effects are distinguished; an eventId reference is not proof of a unique cause.\n\n';
story+='## Financial stories — benchmark-001\n\nPassive: feature development launches Atlas atday64; small contracts begin. Initial95k payroll +10k operating expense outpaces receipts. Under3-month warning atday59, forecast unsafe/under1-month atday151, actual insolvency day181:122 days after the severe warning and30 days after the unsafe next-close indication. Conservative: founder pay10k, sustainable workload, timely payroll downsizing and quality focus → lower burn, then contracts catch up. The same-seed financial branch atday90 survives today455 with NT$605,547 vs control insolvency day181 and NT$−39,834. Recovery is caused by a bundled intervention; its constituent individual effects are measured separately, not attributed solely to quality.\n\nAggressive: hires earlier and launches faster; under3-month signal day15, under1-month/unsafe close day59, insolvency day90. Early signals leave75 and31 days respectively. Monthly earned liabilities explain why stopping recruitment later cannot erase past payroll. No “mathematically inevitable” date is asserted: legal payroll changes, firing and uncertain future contracts can still alter the future. Next-close insufficiency is a conditional financial projection, not proof of inevitability.\n\n';
story+='## Retention story — retention-001\n\nActual command cuts CTO pay to0. Diagnostic exit-intent threshold first crossed day17; observable “有所顧慮” day29 and formal concern day30; stress signal day95; resignation day147. The player receives117 days of formal-concern lead,118 days from the status change, while underlying risk precedes status by12 days. Event factors are compensation0.444, fatigue0.030, satisfaction0.526, loyalty0.000 (numbers remain developer-only). Original UI listed every cause including zero-weight loyalty; projection now omits unsupported zero contributors. The resignation retains related observable salary/concern records without revealing private job search. Branch atday70 restoring40k pay and sustainable prevents resignation for the next120days; no intervention loses CTO. Retention branch cash NT$87,001 vs NT$232,808 for control: keeping a worker costs real money.\n\n';
story+='## Long-lived workload story — lean benchmark-001\n\nStart from a real730-day lean survivor, then change to growth. Observable pressure day849 (119days after change); private exit-risk threshold day987; need-rest category day1023; Carol leaves day1106. Stress-to-departure lead257days; need-rest lead83days. Causes record fatigue and low satisfaction, with zero compensation/loyalty contributors excluded from player projection. Growth raises acquisition chance and near-term output while sustained strain creates later costs. No career, promotion, recruiters or invented conflict was added. Compare the developer-only workload/health recovery branches in warning-traces.json.\n\n';
story+='## Customer uncertainty\n\nThe late growth trace records37 churn events, all classified customer-budget/external; no product-experience churn or prior followup status was observed in this sample. This is a genuine modeled random weekly churn opportunity, not a simulation of a known budget shock. Do not invent customer complaints, a forecast or warning that did not exist. UI now states the recorded classification and its limited evidence. Product satisfaction declines can produce the separate product-experience classification, but these sessions did not validate that path. This is a remaining coverage/product-causality limitation, not hidden success.\n\n';
story+='## Decision sensitivity\n\nSame benchmark-001 origin/day0/command history;90-day comparisons. Hire35k Engineer vs wait: launch50 vs64; cash92,624 vs188,666; monthly payroll +35k. CTO salary50k vs40k: cash158,666 vs188,666, same launch64. Quality vs features: quality branch not launched byday90; feature branch day64 and first revenue. Growth vs sustainable: launch56 vs79; cash197,624 vs187,334, with longer-term health cost investigated separately. Team move changes relationships and observable assignment but produces identical cash/customers/launch byday90; current management/team mechanics have weak direct strategic impact. Full state divergence alone is not presented as economic influence.\n\n';
story+='## Event noise and presentation\n\nPayrollProcessed and FinancialClose form repetitive monthly pairs, while CustomerAcquired/Churned can dominate a long-lived timeline. The raw benchmark records per-type counts, major-event counts and longest spacing; stopped years are not counted as meaningful quiet gameplay. UI retains ALL authoritative events. Inbox defaults to important/warning first with explicit historical-date warning and an off switch; timeline stays chronological and can filter critical/warning/important/informational. Employee-related causes and prior observations link without fabricating causal edges. Weekly summaries list up to4 prioritized actual new events, money/MRR/product/people/customer differences and current alerts. Daily steps do not interrupt. No new narrative author or artificial drama.\n\n';
story+='## Warning evidence\n\n|Trace|Underlying onsets (diagnostic only)|Observable first signals|Negative outcome|\n|---|---|---|---|\n';
for(const t of warnings.traces)story+=`|${t.name}|${t.underlying.map(e=>`${e.id}:${e.risk}@${e.tick}`).join('; ')||'none sampled'}|${t.signals.filter(s=>s.kind!=='customer-followup').map(s=>`${s.kind}${s.condition?':'+s.condition:''}@${s.tick}`).join('; ')}|${t.outcomes.filter(e=>['EmployeeResigned','CompanyBankrupt'].includes(e.type)).map(e=>`${e.type}@${e.tick}`).join('; ')||'none'}|\n`;
story+='\nThe daily traces use separate daily AdvanceTime commands, while policies still decide every14days; command batching changes history/hash but contextual random outcomes remain keyed to tick/entity/seed. Trace hashes independently replay. Initial unsafe-forecast dates depend on future rates held fixed, not probabilistic insolvency prediction.\n';
const pathological=warnings.traces.at(-1),oldWarning=read('warning-traces-before-customer-signal.json').traces.at(-1);
const experience=pathological.outcomes.filter(e=>e.type==='CustomerChurned'&&e.causes.some(c=>c.factor==='product-experience'));
const missing=(trace,event)=>!trace.signals.some(s=>s.kind==='customer-followup'&&s.id===event.payload.customerId&&s.tick<event.tick);
story+=`\n## Product-experience warning sensitivity (diagnostic)\n\nA real default500k/3-person company issues40 zero-salary Engineer hires and growth commands. This deliberately pathological overstaffing scenario is separate from normal player policies; it does not inject world state or fake events. It produces${experience.length} product-experience churn events and40 resignations. Original qualitative customer cutoff missed a prior warning for${experience.filter(e=>missing(oldWarning,e)).length}/${experience.length} experience churn events. Added “體驗轉弱” followed by “需要跟進” reduces this to${experience.filter(e=>missing(pathological,e)).length}/${experience.length} in this trace. All events and final world hash remain identical (${pathological.hash}); only projection signals changed. Raw scores/probabilities are not shown. No guarantee that all seeds or external-budget departures can be warned in advance.\n\nAt day1030, after300days of growth in the real lean survivor, switching to sustainable for180days retains2 workers, restores observable stable categories and ends with cash NT$${fmt(warnings.healthRecovery.a.metrics.cashNTD)}. Continuing growth ends with1 worker, visible need-rest status and cash NT$${fmt(warnings.healthRecovery.b.metrics.cashNTD)}. Recovery has an economic tradeoff: the less humane continuation saves payroll after a resignation and has higher cash. Do not reduce this to a success score.\n`;
writeFileSync(`${dir}/STORY_AUDIT.md`,story);
writeFileSync(`${dir}/BALANCE_CHANGES.md`,'# Phase1.5 balance decisions\n\nNo simulation balance parameters were changed during Phase 1.5.\n\nEvidence: active conservative100% survival and lean73% vs passive3%; early hiring policies fail before recurrent revenue catches up. A35k hire brings launch14days earlier but costs about96k extra cash over90days. Salary burden matters; employee/financial recovery branches respond. These results contradict “no achievable survival path,” so changing cash or acquisition toward50% passive survival is unjustified. The six sampled policies do reveal limited early expansion and weak direct team influence. Those require broader policy/player research, not an arbitrary scalar tweak.\n\nChanged ONLY projections/application feedback/UI and developer tooling: accounting forecast, financial warning categories, nonzero cause evidence, event priorities, actual week delta summary, financial decision previews and causal navigation. No scheduler, RNG, scenario, domain/schema, work, psychology, payroll, acquisition, churn or bankruptcy equation changed. Golden fixtures unchanged; world simulationVersion1/save schema1 preserved. APP_VERSION remains0.1.0 for compatible existing saves. No migration required.\n\nRejected proposals: passive50% target; guaranteed retention; scripted crisis/recovery scenes; raw psychology UI; team productivity bonus without a modeled cause. No before/after balance hash table is needed because no equation changed. Before/after four browser playthrough hashes are compared in final acceptance evidence.\n');
console.log('Generated strategy, playtest, story and balance reports');
